name: AI Autoblog

on:
  schedule:
    # Run every Monday, Wednesday, and Friday at 8:00 AM Pacific
    - cron: "0 15 * * 1,3,5"   # 15:00 UTC = 8:00 AM Pacific (daylight saving)
    - cron: "0 16 * * 1,3,5"   # 16:00 UTC = 8:00 AM Pacific (standard time)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
          SHOPIFY_ADMIN_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ADMIN_ACCESS_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BLOG_HANDLE: ${{ secrets.BLOG_HANDLE }}
          AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
