name: AI Autoblog

on:
  schedule:
    - cron: "0 15 */3 * *"   # Every 3 days at 15:00 UTC (8:00 AM PT)
  workflow_dispatch:          # lets you run it manually

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run autoblog
        env:
          SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
          SHOPIFY_ADMIN_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ADMIN_ACCESS_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BLOG_HANDLE: ${{ secrets.BLOG_HANDLE }}
          AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
        run: |
          python main.py
